---

- name: load system specific vars
  include_vars: "{{ lookup('first_found', params) }}"
  vars:
    params:
      files:
        - "{{ ansible_distribution_release }}.yml"
        - "{{ ansible_distribution }}.yml"
        - "{{ ansible_os_family }}.yml"
        - "default.yml"
      paths:
        - 'vars'

- debug: var=java_package_name

- name: install java package
  package:
    name: "{{ java_package_name }}"
  register: pack_res
  retries: 5
  until: pack_res is success
